### ISSUE TITLE
ILAS(with_counter=True) overflow

### ISSUE THREAD

**Issue by yetifrisstlama** [enjoy-digital/litejesd204b#2]
for `octets_per_multiframe` > 64, the counter producing dummy data overflows > 0xFF, which corrupts the ILAS sequence.

This prevented me from getting the link up on an AD9174.

This fixed it in [link.py](https://github.com/enjoy-digital/litejesd204b/blob/f146048c6cfcbe030f1e616b3153c12bb651ee74/litejesd204b/link.py#L314):
```python
        for i in range(4):
            if with_counter:
                multiframe = [(i * octets_per_multiframe + j) & 0xFF
                    for j in range(octets_per_multiframe)]
```

**Comment by enjoy-digital** [comment]
Thanks for the feedback and fix, this is integrated with https://github.com/enjoy-digital/litejesd204b/commit/2575896e59e608d6b7d661a13bf7be977d079f8f.
