### ISSUE TITLE
phy layer is missing 

### ISSUE THREAD

**Issue by 1n3o1** [enjoy-digital/litejesd204b#4]
thanks in advance
the phy layer of jesd204b is missing form this rep.

PHY: (?)
PRBS7/PRBS15/PRBS31 to check link integrity.
8B/10B encoding
32 bits interface
Artix7 support
Kintex7 support (CPLL up to 5Gbps, QPLL for higher linerates)
Kintex Ultrascale support (CPLL up to 6.25Gbps, QPLL for higher linerates)

**Comment by enjoy-digital** [comment]
Hi,

the PHY layer is common for several cores and is located here: https://github.com/enjoy-digital/liteiclink/tree/master/liteiclink/serdes

You can find an example of integration here: https://gist.github.com/enjoy-digital/cd9ea52fafaebe016e739a90983eb237 (will try to add more examples in the future).
